import type { ICustomTimezone } from "./types/timezone";

const allTimezones: ICustomTimezone = {
  // UTC-11
  "Pacific/Midway": "United States (Midway Island)",
  "Pacific/Niue": "Niue",
  "Pacific/Pago_Pago": "American Samoa",

  // UTC-10
  "Pacific/Honolulu": "United States (Hawaii)",
  "Pacific/Rarotonga": "Cook Islands",
  "Pacific/Tahiti": "French Polynesia",

  // UTC-9:30
  "Pacific/Marquesas": "French Polynesia (Marquesas)",

  // UTC-9
  "America/Anchorage": "United States (Alaska)",
  "America/Juneau": "United States (Alaska - Juneau)",
  "America/Sitka": "United States (Alaska - Sitka)",
  "America/Metlakatla": "United States (Alaska - Annette Island)",
  "America/Yakutat": "United States (Alaska - Yakutat)",
  "America/Nome": "United States (Alaska - Nome)",
  "America/Adak": "United States (Alaska - Aleutians West)",
  "Pacific/Gambier": "French Polynesia (Gambier Islands)",

  // UTC-8
  "America/Los_Angeles": "United States (Pacific Time)",
  "America/Tijuana": "Mexico (Baja California)",
  "America/Vancouver": "Canada (British Columbia)",
  "America/Whitehorse": "Canada (Yukon)",
  "Pacific/Pitcairn": "Pitcairn Islands",

  // UTC-7
  "America/Denver": "United States (Mountain Time)",
  "America/Boise": "United States (Idaho, Oregon)",
  "America/Phoenix": "United States (Arizona)",
  "America/Dawson": "Canada (Yukon - Dawson)",
  "America/Dawson_Creek": "Canada (British Columbia - Dawson Creek)",
  "America/Fort_Nelson": "Canada (British Columbia - Fort Nelson)",
  "America/Edmonton": "Canada (Alberta, Northwest Territories)",
  "America/Cambridge_Bay": "Canada (Nunavut - Cambridge Bay)",
  "America/Inuvik": "Canada (Northwest Territories)",
  "America/Creston": "Canada (British Columbia - Creston)",
  "America/Chihuahua": "Mexico (Chihuahua)",
  "America/Mazatlan": "Mexico (Sinaloa, Nayarit, Baja California Sur)",
  "America/Hermosillo": "Mexico (Sonora)",
  "America/Ciudad_Juarez": "Mexico (Chihuahua - border)",

  // UTC-6
  "America/Chicago": "United States (Central Time)",
  "America/Indiana/Knox": "United States (Indiana - Starke County)",
  "America/Indiana/Tell_City": "United States (Indiana - Perry County)",
  "America/Menominee": "United States (Michigan - Wisconsin border)",
  "America/North_Dakota/Beulah": "United States (North Dakota - Mercer County)",
  "America/North_Dakota/Center": "United States (North Dakota - Oliver County)",
  "America/North_Dakota/New_Salem":
    "United States (North Dakota - Morton County)",
  "America/Winnipeg": "Canada (Manitoba, Nunavut - central)",
  "America/Rainy_River": "Canada (Ontario - Rainy River)",
  "America/Rankin_Inlet": "Canada (Nunavut - central)",
  "America/Resolute": "Canada (Nunavut - Resolute)",
  "America/Regina": "Canada (Saskatchewan)",
  "America/Swift_Current": "Canada (Saskatchewan - Swift Current)",
  "America/Mexico_City": "Mexico (Central)",
  "America/Bahia_Banderas": "Mexico (Bahía de Banderas)",
  "America/Merida": "Mexico (Campeche, Yucatán)",
  "America/Monterrey": "Mexico (Nuevo León, Tamaulipas, Durango)",
  "America/Matamoros": "Mexico (Coahuila, Nuevo León, Tamaulipas - border)",
  "America/Cancun": "Mexico (Quintana Roo)",
  "America/Belize": "Belize",
  "America/Guatemala": "Guatemala",
  "America/Tegucigalpa": "Honduras",
  "America/El_Salvador": "El Salvador",
  "America/Managua": "Nicaragua",
  "America/Costa_Rica": "Costa Rica",
  "Pacific/Easter": "Chile (Easter Island)",
  "Pacific/Galapagos": "Ecuador (Galápagos Islands)",

  // UTC-5
  "America/Detroit": "United States (Eastern Time - Michigan)",
  "America/New_York": "United States (Eastern Time)",
  "America/Indiana/Indianapolis": "United States (Indiana - Eastern)",
  "America/Indiana/Marengo": "United States (Indiana - Crawford County)",
  "America/Indiana/Petersburg": "United States (Indiana - Pike County)",
  "America/Indiana/Vevay": "United States (Indiana - Switzerland County)",
  "America/Indiana/Vincennes": "United States (Indiana - Daviess County)",
  "America/Indiana/Winamac": "United States (Indiana - Pulaski County)",
  "America/Kentucky/Louisville": "United States (Kentucky - Louisville)",
  "America/Kentucky/Monticello": "United States (Kentucky - Wayne County)",
  "America/Toronto": "Canada (Ontario, Quebec)",
  "America/Nipigon": "Canada (Ontario - Nipigon)",
  "America/Thunder_Bay": "Canada (Ontario - Thunder Bay)",
  "America/Iqaluit": "Canada (Nunavut - eastern)",
  "America/Pangnirtung": "Canada (Nunavut - Pangnirtung)",
  "America/Bogota": "Colombia",
  "America/Lima": "Peru",
  "America/Guayaquil": "Ecuador",
  "America/Jamaica": "Jamaica",
  "America/Cayman": "Cayman Islands",
  "America/Panama": "Panama",
  "America/Eirunepe": "Brazil (Amazonas - west)",
  "America/Rio_Branco": "Brazil (Acre)",
  "America/Havana": "Cuba",
  "America/Grand_Turk": "Turks and Caicos Islands",

  // UTC-4
  "America/Halifax": "Canada (Nova Scotia, Prince Edward Island)",
  "America/Glace_Bay": "Canada (Nova Scotia - Cape Breton)",
  "America/Moncton": "Canada (New Brunswick)",
  "America/Goose_Bay": "Canada (Labrador)",
  "America/Blanc-Sablon": "Canada (Quebec - Lower North Shore)",
  "America/Puerto_Rico": "Puerto Rico",
  "America/Port_of_Spain": "Trinidad and Tobago",
  "America/Martinique": "Martinique",
  "America/Barbados": "Barbados",
  "America/St_Lucia": "Saint Lucia",
  "America/St_Vincent": "Saint Vincent and the Grenadines",
  "America/Dominica": "Dominica",
  "America/Antigua": "Antigua and Barbuda",
  "America/St_Kitts": "Saint Kitts and Nevis",
  "America/Montserrat": "Montserrat",
  "America/Grenada": "Grenada",
  "America/Guadeloupe": "Guadeloupe",
  "America/Aruba": "Aruba",
  "America/Curacao": "Curaçao",
  "America/Caracas": "Venezuela",
  "America/La_Paz": "Bolivia",
  "America/Guyana": "Guyana",
  "America/Manaus": "Brazil (Amazonas - east)",
  "America/Boa_Vista": "Brazil (Roraima)",
  "America/Cuiaba": "Brazil (Mato Grosso)",
  "America/Campo_Grande": "Brazil (Mato Grosso do Sul)",
  "America/Anguilla": "Anguilla",
  "America/Tortola": "British Virgin Islands",
  "America/St_Thomas": "U.S. Virgin Islands",
  "America/Kralendijk": "Caribbean Netherlands",
  "America/Marigot": "Saint Martin",
  "America/Lower_Princes": "Sint Maarten",
  "America/Santo_Domingo": "Dominican Republic",
  "America/Santiago": "Chile",
  "America/Punta_Arenas": "Chile (Magallanes Region)",
  "America/Asuncion": "Paraguay",

  // UTC-3:30
  "America/St_Johns": "Canada (Newfoundland)",

  // UTC-3
  "America/Sao_Paulo": "Brazil (São Paulo, most areas)",
  "America/Fortaleza": "Brazil (Northeast)",
  "America/Recife": "Brazil (Pernambuco)",
  "America/Belem": "Brazil (Pará, Amapá)",
  "America/Maceio": "Brazil (Alagoas, Sergipe)",
  "America/Bahia": "Brazil (Bahia)",
  "America/Araguaina": "Brazil (Tocantins)",
  "America/Santarem": "Brazil (Pará - west)",
  "America/Argentina/Buenos_Aires": "Argentina (Buenos Aires)",
  "America/Argentina/Cordoba": "Argentina (Córdoba, most areas)",
  "America/Argentina/Salta": "Argentina (Salta, La Pampa, Neuquén, Río Negro)",
  "America/Argentina/Jujuy": "Argentina (Jujuy)",
  "America/Argentina/Tucuman": "Argentina (Tucumán)",
  "America/Argentina/Catamarca": "Argentina (Catamarca, Chubut)",
  "America/Argentina/La_Rioja": "Argentina (La Rioja)",
  "America/Argentina/San_Juan": "Argentina (San Juan)",
  "America/Argentina/Mendoza": "Argentina (Mendoza)",
  "America/Argentina/San_Luis": "Argentina (San Luis)",
  "America/Argentina/Rio_Gallegos": "Argentina (Santa Cruz)",
  "America/Argentina/Ushuaia": "Argentina (Tierra del Fuego)",
  "America/Montevideo": "Uruguay",
  "America/Cayenne": "French Guiana",
  "America/Paramaribo": "Suriname",
  "America/Miquelon": "Saint Pierre and Miquelon",
  "America/Godthab": "Greenland (most areas)",
  "America/Nuuk": "Greenland",
  "America/Thule": "Greenland (Thule Air Base)",
  "Atlantic/Stanley": "Falkland Islands",
  "Atlantic/South_Georgia": "South Georgia and the South Sandwich Islands",

  // UTC-2
  "America/Noronha": "Brazil (Fernando de Noronha)",

  // UTC-1
  "Atlantic/Azores": "Portugal (Azores)",
  "Atlantic/Cape_Verde": "Cape Verde",

  // UTC+0
  "Europe/London": "United Kingdom",
  "Europe/Dublin": "Ireland",
  "Europe/Lisbon": "Portugal",
  "Africa/Abidjan":
    "Ivory Coast, Burkina Faso, Ghana, Guinea, Mali, Mauritania, Senegal, Sierra Leone, Togo",
  "Africa/Accra": "Ghana",
  "Africa/Monrovia": "Liberia",
  "Africa/Bissau": "Guinea-Bissau",
  "Africa/Casablanca": "Morocco",
  "Africa/El_Aaiun": "Western Sahara",
  "Africa/Sao_Tome": "São Tomé and Príncipe",
  "Atlantic/Canary": "Spain (Canary Islands)",
  "Atlantic/Faroe": "Faroe Islands",
  "Atlantic/Madeira": "Portugal (Madeira)",
  "Atlantic/Reykjavik": "Iceland",
  "America/Danmarkshavn": "Greenland (Danmarkshavn)",

  // UTC+1
  "Europe/Amsterdam": "Netherlands",
  "Europe/Andorra": "Andorra",
  "Europe/Belgrade": "Serbia",
  "Europe/Berlin": "Germany",
  "Europe/Bratislava": "Slovakia",
  "Europe/Brussels": "Belgium",
  "Europe/Budapest": "Hungary",
  "Europe/Busingen": "Germany (Büsingen)",
  "Europe/Copenhagen": "Denmark",
  "Europe/Gibraltar": "Gibraltar",
  "Europe/Ljubljana": "Slovenia",
  "Europe/Luxembourg": "Luxembourg",
  "Europe/Madrid": "Spain",
  "Europe/Malta": "Malta",
  "Europe/Monaco": "Monaco",
  "Europe/Oslo": "Norway",
  "Europe/Paris": "France",
  "Europe/Podgorica": "Montenegro",
  "Europe/Prague": "Czech Republic",
  "Europe/Rome": "Italy",
  "Europe/San_Marino": "San Marino",
  "Europe/Sarajevo": "Bosnia and Herzegovina",
  "Europe/Skopje": "North Macedonia",
  "Europe/Stockholm": "Sweden",
  "Europe/Tirane": "Albania",
  "Europe/Vaduz": "Liechtenstein",
  "Europe/Vatican": "Vatican City",
  "Europe/Vienna": "Austria",
  "Europe/Warsaw": "Poland",
  "Europe/Zagreb": "Croatia",
  "Europe/Zurich": "Switzerland",
  "Africa/Algiers": "Algeria",
  "Africa/Bangui": "Central African Republic",
  "Africa/Brazzaville": "Republic of the Congo",
  "Africa/Ceuta": "Spain (Ceuta, Melilla)",
  "Africa/Douala": "Cameroon",
  "Africa/Kinshasa": "DR Congo (West)",
  "Africa/Lagos": "Nigeria, Niger, Benin, Equatorial Guinea, Gabon",
  "Africa/Libreville": "Gabon",
  "Africa/Luanda": "Angola",
  "Africa/Malabo": "Equatorial Guinea",
  "Africa/Ndjamena": "Chad",
  "Africa/Niamey": "Niger",
  "Africa/Porto-Novo": "Benin",
  "Africa/Tunis": "Tunisia",

  // UTC+2
  "Europe/Athens": "Greece",
  "Europe/Bucharest": "Romania",
  "Europe/Chisinau": "Moldova",
  "Europe/Helsinki": "Finland",
  "Europe/Kaliningrad": "Russia (Kaliningrad)",
  "Europe/Kyiv": "Ukraine",
  "Europe/Mariehamn": "Finland (Åland Islands)",
  "Europe/Nicosia": "Cyprus",
  "Europe/Riga": "Latvia",
  "Europe/Sofia": "Bulgaria",
  "Europe/Tallinn": "Estonia",
  "Europe/Uzhgorod": "Ukraine (Zakarpattia)",
  "Europe/Vilnius": "Lithuania",
  "Europe/Zaporozhye": "Ukraine (Zaporizhzhia)",
  "Africa/Blantyre": "Malawi",
  "Africa/Bujumbura": "Burundi",
  "Africa/Cairo": "Egypt",
  "Africa/Gaborone": "Botswana",
  "Africa/Harare": "Zimbabwe",
  "Africa/Johannesburg": "South Africa, Lesotho, Eswatini",
  "Africa/Juba": "South Sudan",
  "Africa/Khartoum": "Sudan",
  "Africa/Kigali": "Rwanda",
  "Africa/Lubumbashi": "DR Congo (East)",
  "Africa/Lusaka": "Zambia",
  "Africa/Maputo": "Mozambique",
  "Africa/Maseru": "Lesotho",
  "Africa/Mbabane": "Eswatini",
  "Africa/Tripoli": "Libya",
  "Africa/Windhoek": "Namibia",
  "Asia/Jerusalem": "Israel",
  "Asia/Amman": "Jordan",
  "Asia/Beirut": "Lebanon",
  "Asia/Damascus": "Syria",
  "Asia/Famagusta": "Cyprus (Famagusta)",
  "Asia/Gaza": "Palestine (Gaza)",
  "Asia/Hebron": "Palestine (West Bank)",

  // UTC+3
  "Europe/Istanbul": "Turkey",
  "Europe/Kirov": "Russia (Kirov Oblast)",
  "Europe/Minsk": "Belarus",
  "Europe/Moscow": "Russia (Moscow, western)",
  "Europe/Simferopol": "Ukraine (Crimea)",
  "Europe/Volgograd": "Russia (Volgograd)",
  "Africa/Addis_Ababa": "Ethiopia",
  "Africa/Asmara": "Eritrea",
  "Africa/Dar_es_Salaam": "Tanzania",
  "Africa/Djibouti": "Djibouti",
  "Africa/Kampala": "Uganda",
  "Africa/Mogadishu": "Somalia",
  "Africa/Nairobi": "Kenya, Somalia, Tanzania, Uganda, Ethiopia",
  "Asia/Aden": "Yemen",
  "Asia/Baghdad": "Iraq",
  "Asia/Bahrain": "Bahrain",
  "Asia/Kuwait": "Kuwait",
  "Asia/Qatar": "Qatar",
  "Asia/Riyadh": "Saudi Arabia",
  "Indian/Antananarivo": "Madagascar",
  "Indian/Comoro": "Comoros",
  "Indian/Mayotte": "Mayotte",

  // UTC+3:30
  "Asia/Tehran": "Iran",

  // UTC+4
  "Asia/Baku": "Azerbaijan",
  "Asia/Dubai": "United Arab Emirates",
  "Asia/Muscat": "Oman",
  "Asia/Tbilisi": "Georgia",
  "Asia/Yerevan": "Armenia",
  "Europe/Astrakhan": "Russia (Astrakhan Oblast)",
  "Europe/Samara": "Russia (Samara Oblast)",
  "Europe/Saratov": "Russia (Saratov Oblast)",
  "Europe/Ulyanovsk": "Russia (Ulyanovsk Oblast)",
  "Indian/Mahe": "Seychelles",
  "Indian/Mauritius": "Mauritius",
  "Indian/Reunion": "Réunion",

  // UTC+4:30
  "Asia/Kabul": "Afghanistan",

  // UTC+5
  "Asia/Yekaterinburg": "Russia (Yekaterinburg)",
  "Asia/Karachi": "Pakistan",
  "Asia/Tashkent": "Uzbekistan",
  "Asia/Samarkand": "Uzbekistan (Samarkand)",
  "Asia/Dushanbe": "Tajikistan",
  "Asia/Ashgabat": "Turkmenistan",
  "Asia/Atyrau": "Kazakhstan (Atyrau)",
  "Asia/Oral": "Kazakhstan (West Kazakhstan)",
  "Asia/Aqtau": "Kazakhstan (Mangystau)",
  "Asia/Aqtobe": "Kazakhstan (Aqtöbe)",
  "Indian/Kerguelen": "French Southern and Antarctic Lands",
  "Indian/Maldives": "Maldives",

  // UTC+5:30
  "Asia/Kolkata": "India",
  "Asia/Colombo": "Sri Lanka",

  // UTC+5:45
  "Asia/Kathmandu": "Nepal",

  // UTC+6
  "Asia/Almaty": "Kazakhstan (eastern)",
  "Asia/Bishkek": "Kyrgyzstan",
  "Asia/Dhaka": "Bangladesh",
  "Asia/Omsk": "Russia (Omsk Oblast)",
  "Asia/Qostanay": "Kazakhstan (Kostanay)",
  "Asia/Qyzylorda": "Kazakhstan (Kyzylorda)",
  "Asia/Thimphu": "Bhutan",
  "Asia/Urumqi": "China (Xinjiang)",
  "Indian/Chagos": "British Indian Ocean Territory",
  "Indian/Cocos": "Cocos (Keeling) Islands",

  // UTC+6:30
  "Asia/Rangoon": "Myanmar",
  "Asia/Yangon": "Myanmar",

  // UTC+7
  "Asia/Bangkok": "Thailand",
  "Asia/Ho_Chi_Minh": "Vietnam",
  "Asia/Jakarta": "Indonesia (Java, Sumatra)",
  "Asia/Phnom_Penh": "Cambodia",
  "Asia/Pontianak": "Indonesia (West Kalimantan)",
  "Asia/Vientiane": "Laos",
  "Asia/Krasnoyarsk": "Russia (Krasnoyarsk)",
  "Asia/Barnaul": "Russia (Altai Krai)",
  "Asia/Hovd": "Mongolia (Hovd)",
  "Asia/Novokuznetsk": "Russia (Kemerovo Oblast)",
  "Asia/Novosibirsk": "Russia (Novosibirsk Oblast)",
  "Asia/Tomsk": "Russia (Tomsk Oblast)",
  "Indian/Christmas": "Christmas Island",

  // UTC+8
  "Asia/Shanghai": "China",
  "Asia/Chongqing": "China (Chongqing)",
  "Asia/Harbin": "China (Heilongjiang)",
  "Asia/Hong_Kong": "Hong Kong",
  "Asia/Kuala_Lumpur": "Malaysia",
  "Asia/Kuching": "Malaysia (Sarawak)",
  "Asia/Macau": "Macau",
  "Asia/Makassar": "Indonesia (Central & South Kalimantan, Sulawesi)",
  "Asia/Manila": "Philippines",
  "Asia/Singapore": "Singapore",
  "Asia/Taipei": "Taiwan",
  "Asia/Ulaanbaatar": "Mongolia",
  "Asia/Irkutsk": "Russia (Irkutsk Oblast)",
  "Australia/Perth": "Australia (Western Australia)",
  "Australia/Eucla": "Australia (Western Australia - Eucla",
  "Asia/Brunei": "Brunei",

  // UTC+9
  "Asia/Seoul": "South Korea",
  "Asia/Tokyo": "Japan",
  "Asia/Pyongyang": "North Korea",
  "Asia/Chita": "Russia (Zabaykalsky Krai)",
  "Asia/Dili": "Timor-Leste",
  "Asia/Jayapura": "Indonesia (Papua)",
  "Asia/Khandyga": "Russia (Sakha - Khandyga)",
  "Asia/Yakutsk": "Russia (Yakutsk)",
  "Pacific/Palau": "Palau",

  // UTC+9:30
  "Australia/Darwin": "Australia (Northern Territory)",
  "Australia/Adelaide": "Australia (South Australia)",
  "Australia/Broken_Hill": "Australia (New South Wales - Broken Hill)",

  // UTC+10
  "Australia/Sydney": "Australia (New South Wales, Victoria, Tasmania)",
  "Australia/Melbourne": "Australia (Victoria)",
  "Australia/Brisbane": "Australia (Queensland)",
  "Australia/Hobart": "Australia (Tasmania)",
  "Australia/Lindeman": "Australia (Queensland - Whitsunday Islands)",
  "Asia/Vladivostok": "Russia (Vladivostok)",
  "Asia/Ust-Nera": "Russia (Sakha - Ust-Nera)",
  "Pacific/Chuuk": "Micronesia (Chuuk)",
  "Pacific/Guam": "Guam",
  "Pacific/Port_Moresby": "Papua New Guinea",
  "Pacific/Saipan": "Northern Mariana Islands",

  // UTC+10:30
  "Australia/Lord_Howe": "Australia (Lord Howe Island)",

  // UTC+11
  "Asia/Magadan": "Russia (Magadan Oblast)",
  "Asia/Sakhalin": "Russia (Sakhalin Oblast)",
  "Asia/Srednekolymsk": "Russia (Sakha - Srednekolymsk)",
  "Pacific/Bougainville": "Papua New Guinea (Bougainville)",
  "Pacific/Efate": "Vanuatu",
  "Pacific/Guadalcanal": "Solomon Islands",
  "Pacific/Kosrae": "Micronesia (Kosrae)",
  "Pacific/Noumea": "New Caledonia",
  "Pacific/Pohnpei": "Micronesia (Pohnpei)",
  "Pacific/Norfolk": "Norfolk Island",

  // UTC+12
  "Asia/Anadyr": "Russia (Chukotka)",
  "Asia/Kamchatka": "Russia (Kamchatka)",
  "Pacific/Auckland": "New Zealand",
  "Pacific/Fiji": "Fiji",
  "Pacific/Funafuti": "Tuvalu",
  "Pacific/Kwajalein": "Marshall Islands",
  "Pacific/Majuro": "Marshall Islands",
  "Pacific/Nauru": "Nauru",
  "Pacific/Tarawa": "Kiribati (Gilbert Islands)",
  "Pacific/Wake": "United States (Wake Island)",
  "Pacific/Wallis": "Wallis and Futuna",

  // UTC+12:45
  "Pacific/Chatham": "New Zealand (Chatham Islands)",

  // UTC+13
  "Pacific/Apia": "Samoa",
  "Pacific/Fakaofo": "Tokelau",
  "Pacific/Tongatapu": "Tonga",

  // UTC+14
  "Pacific/Kiritimati": "Kiribati (Line Islands)",
};

export default allTimezones;
